version: "3.8"
services:
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    volumes:
      - ./config:/config
    restart: unless-stopped
    environment:
      - "LOGIN=${LOGIN}"
      - "PASSWORD=${PASSWORD}"
    ports:
      - 80:80