version: "3.8"
services:
  ddns-refresh:
    build:
      context: .
      dockerfile : Dockerfile
    container_name: ddns-refresh
    init: true  # workaround for bug crond https://github.com/dubiousjim/dcron/issues/13
    restart: unless-stopped
    environment:
      - "LOGIN=${LOGIN}"
      - "PASSWORD=${PASSWORD}"
    ports:
      - 8245:8245